# Imagen base con Java
FROM eclipse-temurin:21-jdk

# Directorio de trabajo
WORKDIR /app

# Copiar proyecto
COPY . .

# Dar permisos al wrapper de Maven
RUN chmod +x mvnw

# Compilar el proyecto
RUN ./mvnw clean package -DskipTests

# Exponer el puerto
EXPOSE 8080

# Ejecutar la app
CMD ["java", "-jar", "target/crud-0.0.1-SNAPSHOT.jar"]
